import { useEffect } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react'
import { projects } from '../data/siteData'
import ProductVisual from '../components/ProductVisual'
import ArchitectureDiagram from '../components/ArchitectureDiagram'

export default function CaseStudyPage(){const {slug}=useParams();const project=projects.find(p=>p.slug===slug);useEffect(()=>{window.scrollTo(0,0); if(project)document.title=`${project.title} Case Study | Portfolio`},[project]);if(!project)return <Navigate to="/"/>;const index=projects.indexOf(project),next=projects[(index+1)%projects.length];return <motion.main className="case-study" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><header className="case-nav"><Link to="/#work"><ArrowLeft/> All work</Link><span>{project.category}</span></header><section className="case-hero"><div><p className="eyebrow">Case study · 0{index+1}</p><h1>{project.title}</h1><p>{project.description}</p><div className="chips">{project.technologies.map(x=><span key={x}>{x}</span>)}</div></div><ProductVisual project={project}/></section><div className="case-layout"><aside>{['Overview','Challenge','Solution','Features','Architecture','Outcome'].map(x=><a href={`#case-${x.toLowerCase()}`} key={x}>{x}</a>)}</aside><div className="case-content"><section id="case-overview"><p className="eyebrow">Overview</p><h2>Software shaped around the operation.</h2><p className="large-copy">{project.description}</p><div className="case-two"><div><span>My role</span>{project.involvement.map(x=><p key={x}>{x}</p>)}</div><div><span>Users & roles</span>{project.roles.map(x=><p key={x}>{x}</p>)}</div></div></section><section id="case-challenge"><p className="eyebrow">The challenge</p><h2>{project.problem}</h2></section><section id="case-solution"><p className="eyebrow">The solution</p><h2>{project.solution}</h2><ProductVisual project={project} compact/></section><section id="case-features"><p className="eyebrow">Key features</p><h2>Designed as a system, not a collection of screens.</h2><div className="feature-grid">{project.features.map((x,i)=><motion.div initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:(i%4)*.05}} key={x}><CheckCircle2/><span>{x}</span></motion.div>)}</div></section><section id="case-architecture"><p className="eyebrow">Architecture</p><h2>A production-minded delivery path.</h2><ArchitectureDiagram/></section><section id="case-outcome"><p className="eyebrow">Outcome</p><h2>{project.outcome}</h2><p>Built with maintainability, real user roles and evolving operational requirements in mind.</p></section></div></div><Link to={`/work/${next.slug}`} className="next-project"><span>Next project</span><strong>{next.title}</strong><ArrowRight/></Link></motion.main>}
